xsctyaml.bbclass: Fix PYTHON_SITEPACKAGES_DIR
This class is copied from xilinx-tools layer because
the following fix is required.
This change is requested to be merged in upstream.
See: https://lists.yoctoproject.org/pipermail/meta-xilinx/2018-August/004018.html

PYTHON_SITEPACKAGES_DIR is set to /usr/lib64/python3.5/site-packages
but python native is at /usr/lib/ not in /usr/lib64. Which causes
the following error:

ERROR: fsbl-2018.2+gitAUTOINC+6e82c0183b-r0 do_create_yaml: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function:
 0001:
 *** 0002:do_create_yaml(d)
 0003:
File: '/data/hkarim/elm-06/meta-xilinx-tools/classes/xsctyaml.bbclass', lineno: 64, function: do_create_yaml
 0060:
 0061:python do_create_yaml() {
 0062:import sys, os
 0063:os.sys.path.append(os.path.join(d.getVar('RECIPE_SYSROOT_NATIVE'),d.getVar('PYTHON_SITEPACKAGES_DIR')[1::]))
 *** 0064:import yaml
 0065:yaml_dict = {}
 0066:
 0067:appconfig = (d.getVar("YAML_APP_CONFIG", True) or "").split()
 0068:if appconfig:
Exception: ImportError: No module named 'yaml'

ERROR: fsbl-2018.2+gitAUTOINC+6e82c0183b-r0 do_create_yaml: Function failed: do_create_yaml
ERROR: Logfile of failure stored in: /data/hkarim/elm-06/build_uz_2018.3_xlnx/tmp/work/ultrazed_eg_iocc_mel-mel-linux/fsbl/2018.2+gitAUTOINC+6e82c0183b-r0/temp/log.do_create_yaml.4281
ERROR: Task (/data/hkarim/elm-06/meta-xilinx-tools/recipes-bsp/fsbl/fsbl_git.bb:do_create_yaml) failed with exit code '1'

Signed-off-by: abdulkarim17 <hafizabdul_karim@mentor.com>