cyclone5: fix wks files
mountpoint is no longer an optional argument for the part command.
Specify empty mountpoint for the special partition we use for
U-Boot SPL binary.

This fixes:
Error: mel/meta-mentor/meta-mel/scripts/lib/wic/canned-wks/Cyclone-V-4g.wks:7: too few arguments

JIRA: SB-7096

Signed-off-by: Abdur Rehman <abdur_rehman@mentor.com>