toaster-layers-recipes-config: Fix issue for Ubuntu 16.04
Instead of passing layer_and_recipes to iterator, it's
better to convert it into list and pass the keys explicitely.
This fixes the issue caused:

Creating toaster configuration
Traceback (most recent call last):
  File "/home/qatools/akif/mpsoc_tc3/mel/2017.02.67/meta-mentor/scripts/toaster-layers-recipes-config.py", line 43, in <module>
    for layername in layer_and_recipes:
RuntimeError: OrderedDict mutated during iteration

JIRA: SB-8480

Signed-off-by: Sujith Haridasan <Sujith_Haridasan@mentor.com>