mel.conf: Revert PDK_DISTRO_VERSION changes due to license failure.
* PDK_DISTRO_VERSION is used to checkout license. Faced the following error
  ERROR: MEL PDK license check failed: error: (null)
  cs-license failed, aborting

  Reverted old value of PDK_DISTRO_VERSION. Set ARCHIVE_RELEASE_VERSION to
  3 number scheme temprarily.

Signed-off-by: Noor Ahsan <noor_ahsan@mentor.com>