cve-check/cve-update-db-native: Pull initial commit from oe-core to get new fixes.
* Upstream fixed use lockfile to fix usage under multiconfig in commit
  f08604d27ecacfd37bd37bfaf4c76f17b8f65604.
  ERROR: cve-update-db-native-1.0-r0 do_populate_cve_db: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_populate_cve_db(d)
     0003:
File: '/home/ashish/mgc/embedded/nano_tc2/mel-flex-os/12/workspace/oe-core/meta/recipes-core/meta/cve-update-db-native.bb', lineno: 109, function: do_populate_cve_db
     0105:        if year == date.today().year:
     0106:            cve_f.write('CVE database update : %s\n\n' % date.today())
     0107:
     0108:    cve_f.close()
 *** 0109:    conn.commit()
     0110:    conn.close()
     0111:}
     0112:
     0113:def initialize_db(c):
Exception: sqlite3.OperationalError: disk I/O error

* SB-16514

* Initial comnit from oe-core commit 37a40c30709bf80c74948f47361b2be2c646c9d8

Signed-off-by: Noor Ahsan <noor_ahsan@mentor.com>