lttng-modules: fix: jbd2: use the correct print format
post kernel update from v5.4.228..v5.4.229, the commit -
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.4.y&id=ecb9d0d2e123874bcdd2efdecda0f4e0c3dc566d
is causing lttng-modules comilation issue,
for resolving it, the following commits are needed from UPSTREAM lttng-modules v2.12 branch -
https://github.com/lttng/lttng-modules/commit/38b4e82d9f77265f80ea77f809eb354ff6c0f6e4
https://github.com/lttng/lttng-modules/commit/47d24a257b20a3f673f9621ca8d2742b31ff4055

Error:
/home/snaaz/mel/fir/main/build_ull/tmp/work/imx6ullevk_mel-mel-linux-gnueabi/lttng-modules/2.12.2-r0/lttng-modules-2.12.2/probes/../probes/lttng-tracepoint-event-impl.h:131:6: error: conflicting types for 'trace_jbd2_run_stats'
|   131 | void trace_##_name(_proto);
|       |      ^~~~~~
| /home/snaaz/mel/fir/main/build_ull/tmp/work/imx6ullevk_mel-mel-linux-gnueabi/lttng-modules/2.12.2-r0/lttng-modules-2.12.2/probes/../probes/lttng-tracepoint-event-impl.h:43:2: note: in expansion of macro 'LTTNG_TRACEPOINT_EVENT_INSTANCE_MAP'
|    43 |  LTTNG_TRACEPOINT_EVENT_INSTANCE_MAP(map, name, map, PARAMS(proto), PARAMS(args))
|       |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/snaaz/mel/fir/main/build_ull/tmp/work/imx6ullevk_mel-mel-linux-gnueabi/lttng-modules/2.12.2-r0/lttng-modules-2.12.2/probes/../probes/lttng-tracepoint-event-impl.h:85:2: note: in expansion of macro 'LTTNG_TRACEPOINT_EVENT_MAP'
|    85 |  LTTNG_TRACEPOINT_EVENT_MAP(name, name,    \
|       |  ^~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/snaaz/mel/fir/main/build_ull/tmp/work/imx6ullevk_mel-mel-linux-gnueabi/lttng-modules/2.12.2-r0/lttng-modules-2.12.2/probes/../instrumentation/events/lttng-module/jbd2.h:104:1: note: in expansion of macro 'LTTNG_TRACEPOINT_EVENT'
|   104 | LTTNG_TRACEPOINT_EVENT(jbd2_run_stats,
|       | ^~~~~~~~~~~~~~~~~~~~~~
| In file included from /home/snaaz/mel/fir/main/build_ull/tmp/work-shared/imx6ullevk-mel/kernel-source/include/trace/events/jbd2.h:9,
|                  from /home/snaaz/mel/fir/main/build_ull/tmp/work/imx6ullevk_mel-mel-linux-gnueabi/lttng-modules/2.12.2-r0/lttng-modules-2.12.2/probes/lttng-probe-jbd2.c:18:
| /home/snaaz/mel/fir/main/build_ull/tmp/work-shared/imx6ullevk-mel/kernel-source/include/linux/tracepoint.h:243:21: note: previous definition of 'trace_jbd2_run_stats' was here
|   243 |  static inline void trace_##name(proto)    \
|       |                     ^~~~~~
| /home/snaaz/mel/fir/main/build_ull/tmp/work-shared/imx6ullevk-mel/kernel-source/include/linux/tracepoint.h:406:2: note: in expansion of macro '__DECLARE_TRACE'
|   406 |  __DECLARE_TRACE(name, PARAMS(proto), PARAMS(args),  \
|       |  ^~~~~~~~~~~~~~~
| /home/snaaz/mel/fir/main/build_ull/tmp/work-shared/imx6ullevk-mel/kernel-source/include/linux/tracepoint.h:542:2: note: in expansion of macro 'DECLARE_TRACE'
|   542 |  DECLARE_TRACE(name, PARAMS(proto), PARAMS(args))
|       |  ^~~~~~~~~~~~~
| /home/snaaz/mel/fir/main/build_ull/tmp/work-shared/imx6ullevk-mel/kernel-source/include/trace/events/jbd2.h:234:1: note: in expansion of macro 'TRACE_EVENT'
|   234 | TRACE_EVENT(jbd2_run_stats,
|       | ^~~~~~~~~~~

JIRA-ID: SB-21428

Signed-off-by: Syeda Shagufta Naaz <SyedaShagufta_Naaz@mentor.com>