lttng-modules: fix adjust range v5.10.137 in block prob
Error:
| /home/syeda/mel/fir/up6/2async/build_zcu/tmp/work/zcu102_zynqmp_mel-mel-linux/lttng-modules/2.12.2-r0/lttng-modules-2.12.2/probes/../probes/lttng-tracepoint-event-impl.h:131:6: error: conflicting types for 'trace_block_rq_requeue'
|   131 | void trace_##_name(_proto);
|       |      ^~~~~~
| /home/syeda/mel/fir/up6/2async/build_zcu/tmp/work/zcu102_zynqmp_mel-mel-linux/lttng-modules/2.12.2-r0/lttng-modules-2.12.2/probes/../probes/lttng-tracepoint-event-impl.h:43:2: note: in expansion of macro 'LTTNG_TRACEPOINT_EVENT_INSTANCE_MAP'
|    43 |  LTTNG_TRACEPOINT_EVENT_INSTANCE_MAP(map, name, map, PARAMS(proto), PARAMS(args))
|       |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/syeda/mel/fir/up6/2async/build_zcu/tmp/work/zcu102_zynqmp_mel-mel-linux/lttng-modules/2.12.2-r0/lttng-modules-2.12.2/probes/../probes/lttng-tracepoint-event-impl.h:85:2: note: in expansion of macro 'LTTNG_TRACEPOINT_EVENT_MAP'
|    85 |  LTTNG_TRACEPOINT_EVENT_MAP(name, name,    \
|       |  ^~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/syeda/mel/fir/up6/2async/build_zcu/tmp/work/zcu102_zynqmp_mel-mel-linux/lttng-modules/2.12.2-r0/lttng-modules-2.12.2/probes/../instrumentation/events/lttng-module/block.h:279:1: note: in expansion of macro 'LTTNG_TRACEPOINT_EVENT'
|   279 | LTTNG_TRACEPOINT_EVENT(block_rq_requeue,
|       | ^~~~~~~~~~~~~~~~~~~~~~

Introduced by kernel update via commit - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.10.y&id=1cb3032406423b25aa984854b4d78e0100d292dd

Fixed by backporting two commits:
1. An additional commit to support the actual commit as the patch code
and source code didn't match - https://github.com/lttng/lttng-modules/commit/173f7d83002d5e4b47f67c63ee0367011e80333c

2. actual commit which fixes the issue -
https://git.lttng.org/?p=lttng-modules.git;a=patch;h=9f7df0f1867273244e62e14e68e20e03db4902ca

JIRA-ID: SB-20840

Signed-off-by: Syeda Shagufta Naaz <SyedaShagufta_Naaz@mentor.com>