meta-mentor-staging:perf: Remove man package from RDEPENDS of docs.
* Perf doc package is dependent on man and man is dependent on libpipeline.
  Build fails when GPLv3 is addded in INCOMPATIBLE_LICENSE saying following.
  ERROR: Nothing PROVIDES 'libpipeline' (but /data/noor/mel/releases/elm/
  main/oe-core/meta/recipes-extended/man-db/man-db_2.8.1.bb DEPENDS on
  or otherwise requires it)
  The reason for this is we don't non GPLv3 version available for libpipeline.
  man current version is needd libpipeline package. Removed man from
  RPEDENDS_doc when GPLv3 is added in INCOMPATIBLE_LICENSE.

Signed-off-by: Noor Ahsan <noor_ahsan@mentor.com>