python3-scapy: add a required runtime dependency on fcntl
This fixes a runtime issue where scapy complains
ModuleNotFoundError: No module named 'fcntl'

Signed-off-by: Awais Belal <awais_belal@mentor.com>