96boards-tools: resize-helper.service: fix for auto-resizing sd card
JIRA: SB-10112

Upstream-Status: pending

we need PART_ENTRY_NUMBER filled with correct values to fix the resizing
error: partition dosen't exist,

this job will be done by udevadm, so to get expected inputs from it require
systemd-udev-settle.service

This error is so far observed only on below set of sd cards:
i. 8 gb+ class 10 sd cards
ii. 8 gb+ micro sd cards with sd card holder

Signed-off-by: Shrikant Bobade <shrikant_bobade@mentor.com>