python-pygobject: Resolve host-user-contaminated error.
* jenkins was facing following error
 ERROR: QA Issue: python-pygobject: /python-pygobject/usr/lib/python2.7/site-packages/pygtk.pth
 is owned by uid 1000, which is the same as the user running bitbake. This may be due to host contamination [host-user-contaminated]

Signed-off-by: Noor Ahsan <noor_ahsan@mentorg.com>