cve-check: Fix build error when fir initramfs image when built with cve-check class.
* Reapply the previus commit on new file
  meta-mentor commit 6b605ad2c083e6dbe66dd75926a689690613720a
* When INHERIT += "cve-check" is added in local.conf and we build mel-initramfs-image it
  fails with following error

File: 'oe-core/meta/classes/cve-check.bbclass', lineno: 101, function: cve_check_write_rootfs_manifest
     0097:        link_name = d.getVar("IMAGE_LINK_NAME")
     0098:        manifest_name = d.getVar("CVE_CHECK_MANIFEST")
     0099:        cve_tmp_file = d.getVar("CVE_CHECK_TMP_FILE")
     0100:
 *** 0101:        shutil.copyfile(cve_tmp_file, manifest_name)
     0102:
     0103:        if manifest_name and os.path.exists(manifest_name):
     0104:            manifest_link = os.path.join(deploy_dir, "%s.cve" % link_name)
     0105:            # If we already have another manifest, update symlinks
File: '/usr/lib/python3.8/shutil.py', lineno: 261, function: copyfile
     0257:
     0258:    if not follow_symlinks and _islink(src):
     0259:        os.symlink(os.readlink(src), dst)
     0260:    else:
 *** 0261:        with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
     0262:            # macOS
     0263:            if _HAS_FCOPYFILE:
     0264:                try:
     0265:                    _fastcopy_fcopyfile(fsrc, fdst, posix._COPYFILE_DATA)
Exception: FileNotFoundError: [Errno 2] No such file or directory: '...deploy/images/imx6ullevk-mel/mel-initramfs-image-imx6ullevk-mel-20201027144226.rootfs.cve'

 This error occur due to the reason that tmp/deploy/images folder is not created when shutil.copyfile
 function call is executed. That is why /mel-initramfs-image-imx6ullevk-mel-20201027144226.rootfs.cve
 could not be located in tmp/deploy/images folder. Added bb.utils.mkdirhier(deploy_dir) just before
 shutil.copyfile so that tmp/deploy/images/<machine> folder gets created before the function call.

* SB-15623

Signed-off-by: Noor Ahsan <noor_ahsan@mentor.com>